# Generated by Django 4.0 on 2021-12-13 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ('dish_order',)},
        ),
    ]
